// data.js — ATL Events V2 Data Layer
// Events: Apr–Sep 2026 | Evergreen: 75 activities

const TODAY = new Date('2026-04-21');

const EVENTS = [
  {
    id: 1,
    date: '2026-04-24', dateEnd: '2026-04-24', dateStr: 'Fri Apr 24',
    title: 'Patrick Topping',
    subtitle: null,
    venue: 'District Atlanta', address: '180 Walker St SW, Atlanta, GA',
    lat: 33.7490, lng: -84.3890,
    score: 80, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Drumcode techno', 'peak-time house'],
    environment: 'indoor', eventType: 'dj', age: '21+',
    time: '9 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.eventbrite.com/e/patrick-topping-friday-april-24th-2026-district-atlanta-tickets-1982883574148', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: ['Patrick Topping'],
    setTimes: null,
    youtubeId: '-yX-ZtWq7Ec',
    imageUrl: 'images/patrick_topping.jpg', officialUrl: 'https://districtatlanta.com/events/2026/patrick-topping-therapy-sessions-friday-april-24th-2026.php', instagramUrl: 'https://instagram.com/patricktopping',
    note: 'Drumcode artist and Defected heavyweight. Patrick Topping plays groove-led, organic techno and peak-time house — think propulsive rhythms layered over melodic tension. He\'s known for long marathon sets that build relentlessly. District Atlanta suits his style: dark warehouse floor, serious sound system, 21+ crowd that shows up to dance. This is a Friday night with one window to pull it together. Reach out to the crew now.',
    scoreReasoning: { genreMatch: 82, venueQuality: 63, formatRarity: 55, lineupStrength: 76, valueForMoney: 70 },
    recurring: false, recurringNote: null
  },
  {
    id: 2,
    date: '2026-04-25', dateEnd: '2026-04-25', dateStr: 'Sat Apr 25',
    title: 'Shake the Lake',
    subtitle: 'Beats on the Lake — Matt Silliman',
    venue: 'Lake Lanier', address: 'Buford, GA',
    lat: 34.1944, lng: -83.9688,
    score: 78, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Electronic', 'outdoor house'],
    environment: 'outdoor', eventType: 'dj', age: '21+',
    time: 'Afternoon', timeSlot: 'afternoon', distance: 'OTP',
    urgent: true, urgentNote: '~30 tickets left — buy via @mattsilliman_dj BIO now',
    ticketUrl: 'https://www.facebook.com/events/harbor-landing-at-lake-lanier/beats-on-the-lake-presents-shake-the-lake-2026-matt-silliman-brendon-lee-curtis-/1598757727826811/', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: ['Matt Silliman'],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/shake_the_lake.png', officialUrl: 'https://www.beatsonthelake.com/', instagramUrl: 'https://instagram.com/mattsilliman_dj',
    note: 'Matt Silliman takes over a lakeside venue on Lake Lanier for an afternoon of outdoor electronic music — open-air, scenic, and intimate by design. Cash bar on site, BYOB ok, afters typically planned afterward. This is the format that doesn\'t exist often enough: a proper DJ set in nature, not a dark club. ~30 tickets remaining and they will sell — grab now via his Instagram bio.',
    scoreReasoning: { genreMatch: 75, venueQuality: 62, formatRarity: 72, lineupStrength: 65, valueForMoney: 80 },
    recurring: false, recurringNote: null
  },
  {
    id: 3,
    date: '2026-04-25', dateEnd: '2026-04-25', dateStr: 'Sat Apr 25',
    title: 'Inman Park Festival',
    subtitle: 'Free annual neighborhood street fair',
    venue: 'Inman Park', address: 'Inman Park, Atlanta, GA',
    lat: 33.7528, lng: -84.3538,
    score: 74, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Street fair', 'outdoor', 'free'],
    environment: 'outdoor', eventType: 'festival', age: 'All ages',
    time: 'All day', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://inmanparkfestival.org', free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/inman_park_festival.webp', officialUrl: 'https://inmanparkfestival.org', instagramUrl: null,
    note: 'Free annual street fair — food, live music, local art, stroller-friendly. Beltline-adjacent. Perfect Saturday outing with Dean.',
    scoreReasoning: { genreMatch: 45, venueQuality: 62, formatRarity: 65, lineupStrength: 50, valueForMoney: 98 },
    recurring: false, recurringNote: null
  },
  {
    id: 4,
    date: '2026-04-25', dateEnd: '2026-04-25', dateStr: 'Sat Apr 25',
    title: 'Dino Fest',
    subtitle: null,
    venue: 'Stone Mountain Park', address: 'Stone Mountain, GA',
    lat: 33.8057, lng: -84.1700,
    score: 70, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Kids', 'outdoor', 'dinosaurs'],
    environment: 'outdoor', eventType: 'festival', age: 'All ages',
    time: 'All day', timeSlot: 'morning', distance: 'OTP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://stonemountainpark.com/tickets-specials/', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/dino_fest.png', officialUrl: 'https://stonemountainpark.com/activity/events/dino-fest/', instagramUrl: null,
    note: "Outdoor dinosaur event at Stone Mountain. Dean would be absolutely losing it. Pair as a day trip or split with Inman Park Festival.",
    scoreReasoning: { genreMatch: 30, venueQuality: 55, formatRarity: 62, lineupStrength: 40, valueForMoney: 75 },
    recurring: false, recurringNote: null
  },
  {
    id: 5,
    date: '2026-05-01', dateEnd: '2026-05-01', dateStr: 'Fri May 1',
    title: 'Disclosure LIVE',
    subtitle: 'Full live band — not a DJ set',
    venue: 'The Eastern', address: '777 Memorial Dr SE, Atlanta, GA',
    lat: 33.7478, lng: -84.3580,
    score: 95, tier: 'S',
    slots: ['GROUP_NIGHT', 'DATE_NIGHT'],
    category: 'music', genres: ['UK house', 'electronic', 'live band'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: '8 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: true, urgentNote: 'Venue caps ~1,000. Will sell out. Buy this week.',
    ticketUrl: 'https://www.axs.com/events/1281830/disclosure-live-tickets', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: ['Disclosure (LIVE)'],
    setTimes: 'Doors 7 PM · Disclosure 9 PM',
    youtubeId: '93ASUImTedo',
    imageUrl: 'images/disclosure_live.jpg',
    officialUrl: 'https://www.axs.com/events/1281830/disclosure-live-tickets',
    instagramUrl: 'https://instagram.com/disclosuremusic',
    note: 'This is not a DJ set — Disclosure are performing as a full live band with keyboards, live drums, bass, and vocals. Every track you know (Latch, White Noise, You & Me, Magnets) comes alive differently in this format. The Eastern is purpose-built for this: intimate ~1,000 cap, outstanding acoustics, and all-ages access. Two-night Atlanta run — night one is the call. Tickets on AXS, will sell out before the week is over. Block both a date night or a group night if you can.',
    scoreReasoning: { genreMatch: 95, venueQuality: 92, formatRarity: 96, lineupStrength: 98, valueForMoney: 85 },
    recurring: false, recurringNote: null
  },
  {
    id: 14,
    date: '2026-05-01', dateEnd: '2026-05-01', dateStr: 'Fri May 1',
    title: 'Supertask',
    subtitle: null,
    venue: 'Terminal West', address: '887 W Marietta St NW, Atlanta, GA',
    lat: 33.7974, lng: -84.4191,
    score: 78, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Electronic', 'techno'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: '9 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.ticketmaster.com/supertask-atlanta-05-01-2026/event/Z7r9jZ1A7qM7k', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: ['Supertask'],
    setTimes: null,
    youtubeId: null,
    imageUrl: null, officialUrl: 'https://www.axs.com/events/1180694/supertask-tickets', instagramUrl: null,
    note: 'Solid fallback if Disclosure LIVE sells out. Same night — check Terminal West box office.',
    scoreReasoning: { genreMatch: 78, venueQuality: 85, formatRarity: 65, lineupStrength: 70, valueForMoney: 72 },
    recurring: false, recurringNote: null
  },
  {
    id: 15,
    date: '2026-05-01', dateEnd: '2026-05-01', dateStr: 'Fri May 1',
    title: 'Disclosure DJ Set',
    subtitle: 'Night 2 at District Atlanta',
    venue: 'District Atlanta', address: '180 Walker St SW, Atlanta, GA',
    lat: 33.7490, lng: -84.3890,
    score: 80, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['UK house', 'electronic', 'DJ set'],
    environment: 'indoor', eventType: 'dj', age: '21+',
    time: '10 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.eventbrite.com/e/disclosure-dj-set-friday-may-1st-2026-district-atlanta-tickets-1984145780441', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: ['Disclosure (DJ)'],
    setTimes: null,
    youtubeId: '93ASUImTedo',
    imageUrl: 'images/disclosure_dj_set.jpg', officialUrl: 'https://districtatlanta.com/events/2026/disclosure-with-stefan-ringer-dj-set-friday-may-1st-2026.php', instagramUrl: null,
    note: "DJ set vs. live band — clearly secondary option. Same artist, far less special than The Eastern. Go only if Disclosure LIVE sells out.",
    scoreReasoning: { genreMatch: 90, venueQuality: 63, formatRarity: 45, lineupStrength: 85, valueForMoney: 60 },
    recurring: false, recurringNote: null
  },
  {
    id: 6,
    date: '2026-05-07', dateEnd: '2026-05-07', dateStr: 'Wed May 7',
    title: 'Dance With The Dead + Magic Sword',
    subtitle: 'The Face Off Tour 2026',
    venue: 'Terminal West', address: '887 W Marietta St NW, Atlanta, GA',
    lat: 33.7974, lng: -84.4191,
    score: 88, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Synthwave', 'cinematic electronic', 'electronic rock'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: '8 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.axs.com/events/1236462/dance-with-the-dead-magic-sword-tickets', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: ['Magic Sword', 'Dance With The Dead'],
    setTimes: 'Doors 7 PM · DWTD 8 PM · Magic Sword 9:30 PM',
    youtubeId: 'G02wKufX3nw',
    imageUrl: 'images/dance_with_the_dead__magic_sword.jpg',
    officialUrl: 'https://www.axs.com/events/1236462/dance-with-the-dead-magic-sword-tickets',
    instagramUrl: 'https://instagram.com/magicswordband',
    note: 'Two of the most visually distinctive acts in the synthwave world on the same bill. Magic Sword performs masked and hooded — three anonymous musicians playing epic, fantasy-cinematic synthwave built for stadium arenas squeezed into an intimate Terminal West room. Dance With The Dead brings horror-influenced electronic rock: crunching guitar, synth bass, the aesthetic of a John Carpenter score turned into live music. This double headliner format rarely happens. Terminal West at ~900 capacity makes it feel like a secret.',
    scoreReasoning: { genreMatch: 85, venueQuality: 88, formatRarity: 92, lineupStrength: 82, valueForMoney: 88 },
    recurring: false, recurringNote: null
  },
  {
    id: 7,
    date: '2026-05-08', dateEnd: '2026-05-08', dateStr: 'Thu May 8',
    title: 'Vintage Culture',
    subtitle: null,
    venue: 'District Atlanta', address: '180 Walker St SW, Atlanta, GA',
    lat: 33.7490, lng: -84.3890,
    score: 82, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Melodic house', 'deep house', 'Brazilian'],
    environment: 'indoor', eventType: 'dj', age: '21+',
    time: '9 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.eventbrite.com/e/vintage-culture-friday-may-8th-2026-district-atlanta-tickets-1981787423532', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: ['Vintage Culture'],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/vintage_culture.jpg', officialUrl: 'https://districtatlanta.com/events/2026/vintage-culture-therapy-sessions-friday-may-8th-2026.php', instagramUrl: 'https://instagram.com/vintagecultureofficial',
    note: 'Vintage Culture is one of Brazil\'s biggest exports in the melodic house space. His sound: warm basslines, intricate percussion, layered vocals, and an emotional arc that builds across a long set. Think Lane 8 meeting Disclosure on a São Paulo rooftop. He plays extended sets — District Atlanta\'s layout rewards arriving early for the full journey. Thursday night, 21+, the kind of show that turns a weeknight into a story.',
    scoreReasoning: { genreMatch: 84, venueQuality: 63, formatRarity: 60, lineupStrength: 80, valueForMoney: 68 },
    recurring: false, recurringNote: null
  },
  {
    id: 16,
    date: '2026-05-09', dateEnd: '2026-05-09', dateStr: 'Sat May 9',
    title: 'Center for Puppetry Arts',
    subtitle: 'Weekend family performance',
    venue: 'Center for Puppetry Arts', address: '1404 Spring St NW, Atlanta, GA',
    lat: 33.7929, lng: -84.3855,
    score: 67, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Kids', 'theater', 'puppetry'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: '2 PM', timeSlot: 'afternoon', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://puppet.org/visit/', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/center_for_puppetry_arts.gif', officialUrl: 'https://puppet.org', instagramUrl: null,
    note: 'World-class puppet theater with hands-on museum. Dean will be captivated. Book the matinee. Jim Henson collection on site.',
    scoreReasoning: { genreMatch: 35, venueQuality: 68, formatRarity: 72, lineupStrength: 55, valueForMoney: 70 },
    recurring: false, recurringNote: null
  },
  {
    id: 17,
    date: '2026-05-10', dateEnd: '2026-05-10', dateStr: 'Sun May 10',
    title: 'Sol Dance — Ecstatic Dance',
    subtitle: '2nd Sunday monthly · Brook Run Park',
    venue: 'Brook Run Park', address: '4770 N Peachtree Rd, Dunwoody, GA',
    lat: 33.9572, lng: -84.3379,
    score: 72, tier: 'B',
    slots: ['SOLO_RESET'],
    category: 'social', genres: ['Ecstatic dance', 'movement', 'community'],
    environment: 'indoor', eventType: 'recurring', age: 'All ages',
    time: '12–4 PM', timeSlot: 'afternoon', distance: 'OTP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://momence.com/u/sol-dance-movement-EKesBe', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: '12 PM – 4 PM',
    youtubeId: null,
    imageUrl: 'images/sol_dance_ecstatic_dance.jpg', officialUrl: 'https://soldancemovement.com', instagramUrl: null,
    note: 'Non-verbal connection, high-energy movement, sober or not. Physical reset without gym logic. Community spiral energy. The best Sunday investment.',
    scoreReasoning: { genreMatch: 62, venueQuality: 55, formatRarity: 82, lineupStrength: 50, valueForMoney: 85 },
    recurring: true, recurringNote: '2nd Sunday monthly. Next: Jun 14, Jul 12, Aug 9, Sep 13'
  },
  {
    id: 18,
    date: '2026-05-10', dateEnd: '2026-05-10', dateStr: 'Sun May 10',
    title: 'High Museum — Second Sunday',
    subtitle: 'Free community day · Midtown',
    venue: 'High Museum of Art', address: '1280 Peachtree St NE, Atlanta, GA',
    lat: 33.7902, lng: -84.3853,
    score: 70, tier: 'B',
    slots: ['SOLO_RESET', 'DATE_NIGHT'],
    category: 'social', genres: ['Art', 'museum', 'free'],
    environment: 'indoor', eventType: 'recurring', age: 'All ages',
    time: 'Morning', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://high.org', free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/high_museum_second_sunday.jpg', officialUrl: 'https://high.org', instagramUrl: null,
    note: 'Second Sunday of every month — free admission to one of the South\'s best art museums. Go early. Quiet before the crowds arrive.',
    scoreReasoning: { genreMatch: 40, venueQuality: 85, formatRarity: 55, lineupStrength: 60, valueForMoney: 100 },
    recurring: true, recurringNote: '2nd Sunday monthly. Free admission.'
  },
  {
    id: 19,
    date: '2026-05-16', dateEnd: '2026-05-16', dateStr: 'Sat May 16',
    title: 'Dad\'s Garage: Adventure Playhouse',
    subtitle: 'Interactive improv for kids · Family Saturday',
    venue: 'Dad\'s Garage Theatre', address: '569 Ezzard St SE, Atlanta, GA',
    lat: 33.7349, lng: -84.3635,
    score: 65, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'comedy', genres: ['Improv', 'kids theater', 'interactive'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: '11 AM', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://dadsgarage.my.salesforce-sites.com/ticket/PatronTicket__PublicTicketApp', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/dad_s_garage_adventure_playhouse.png', officialUrl: 'https://dadsgarage.com', instagramUrl: null,
    note: 'Kid-focused interactive improv. Dean gets to participate. Morning slot keeps it naptime-safe. Dad\'s Garage is a classic ATL venue.',
    scoreReasoning: { genreMatch: 35, venueQuality: 62, formatRarity: 70, lineupStrength: 50, valueForMoney: 78 },
    recurring: true, recurringNote: 'Runs most Saturdays — check dadsgarage.com'
  },
  {
    id: 8,
    date: '2026-05-15', dateEnd: '2026-05-15', dateStr: 'Thu May 15',
    title: 'Sub Focus — 360° Set',
    subtitle: 'Funktion-One 4-corner surround · The Gallery',
    venue: 'Underground Atlanta', address: '50 Upper Alabama St SW, Atlanta, GA',
    lat: 33.7495, lng: -84.3917,
    score: 95, tier: 'S',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Drum & bass', 'liquid D&B', '360° immersive'],
    environment: 'indoor', eventType: 'dj', age: '18+',
    time: '9 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: true, urgentNote: 'LIMITED CAPACITY. First ATL show since 2018. Sells out this week.',
    ticketUrl: 'https://www.ticketfairy.com/event/sub-focus-360', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: ['Sub Focus', 'BLOSSOM', 'Ghost in Real Life', 'D:RC', 'RUNNA', 'PLATEZ'],
    setTimes: 'PLATEZ 9 PM · RUNNA 10 PM · D:RC 11 PM · Ghost in Real Life 12 AM · BLOSSOM 1 AM · Sub Focus 2 AM',
    youtubeId: '6-cUGj05OAc',
    imageUrl: 'images/sub_focus_360.jpg',
    officialUrl: 'https://www.ticketfairy.com/event/sub-focus-360',
    instagramUrl: 'https://instagram.com/subfocus',
    note: 'The Gallery (Underground ATL) has been configured with a custom 4-corner Funktion-One speaker array — the 360° format means the music moves around the room, not just at you from a stage. Sub Focus pioneered this format in the D&B world and this is his first Atlanta appearance in eight years. He headlines at 2 AM after a packed support lineup starting at 9 PM. Liquid drum & bass at its emotional peak — melodic, driving, and engineered to floor you. 18+, limited capacity, this sells before the weekend.',
    scoreReasoning: { genreMatch: 95, venueQuality: 100, formatRarity: 100, lineupStrength: 92, valueForMoney: 90 },
    recurring: false, recurringNote: null
  },
  {
    id: 9,
    date: '2026-05-18', dateEnd: '2026-05-18', dateStr: 'Sun May 18',
    title: 'Chet Faker',
    subtitle: null,
    venue: 'The Masquerade', address: '311 Trestle Ave NE, Atlanta, GA',
    lat: 33.7453, lng: -84.3727,
    score: 76, tier: 'A',
    slots: ['GROUP_NIGHT', 'DATE_NIGHT'],
    category: 'music', genres: ['Electronic', 'R&B', 'soul'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: 'Evening', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.ticketmaster.com/chet-faker-atlanta-georgia-05-18-2026/event/0E006356FA8FA07B', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: ['Chet Faker'],
    setTimes: null,
    youtubeId: 'hi4pzKvuEQM',
    imageUrl: 'images/chet_faker.jpg', officialUrl: 'https://www.masqueradeatlanta.com/events/chet-faker/', instagramUrl: 'https://instagram.com/chetfaker',
    note: 'Soulful electronic/R&B from the Hidden artist. Mellow Sunday option — works as a date night or a relaxed group show.',
    scoreReasoning: { genreMatch: 72, venueQuality: 70, formatRarity: 65, lineupStrength: 75, valueForMoney: 75 },
    recurring: false, recurringNote: null
  },
  {
    id: 20,
    date: '2026-05-22', dateEnd: '2026-05-22', dateStr: 'Fri May 22',
    title: 'Lake Claire Full Moon Drum Circle',
    subtitle: 'Monthly · Full moon gathering',
    venue: 'Lake Claire Land Trust', address: 'Lake Claire, Atlanta, GA',
    lat: 33.7666, lng: -84.3306,
    score: 63, tier: 'B',
    slots: ['GROUP_NIGHT', 'SOLO_RESET'],
    category: 'social', genres: ['Community', 'drum circle', 'outdoor', 'free'],
    environment: 'outdoor', eventType: 'recurring', age: 'All ages',
    time: 'Dusk–10 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: null, free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/lake_claire_full_moon_drum_circle.jpg', officialUrl: 'https://www.lcclt.org/new-events/7sljklmp5l9fba2', instagramUrl: null,
    note: 'Full moon drum circle at Lake Claire Land Trust. Bring a drum or just show up. Free, open, no experience needed. ATL community ritual.',
    scoreReasoning: { genreMatch: 38, venueQuality: 55, formatRarity: 75, lineupStrength: 25, valueForMoney: 100 },
    recurring: true, recurringNote: 'Monthly on the full moon'
  },
  {
    id: 10,
    date: '2026-05-23', dateEnd: '2026-05-23', dateStr: 'Sat May 23',
    title: 'Atlanta Jazz Festival',
    subtitle: 'Free outdoor · Memorial Day Weekend',
    venue: 'Piedmont Park', address: 'Piedmont Park, Atlanta, GA',
    lat: 33.7869, lng: -84.3734,
    score: 74, tier: 'B',
    slots: ['FAMILY_OUT', 'GROUP_NIGHT'],
    category: 'family', genres: ['Jazz', 'outdoor', 'free'],
    environment: 'outdoor', eventType: 'festival', age: 'All ages',
    time: 'Afternoon', timeSlot: 'afternoon', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.atlantajazzfestival.com', free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/atlanta_jazz_festival.jpg', officialUrl: 'https://www.atlantajazzfestival.com', instagramUrl: null,
    note: 'Free outdoor jazz festival in Piedmont Park. Memorial Day Weekend. Family-friendly — bring Dean, lay out a blanket, let the afternoon breathe.',
    scoreReasoning: { genreMatch: 55, venueQuality: 72, formatRarity: 60, lineupStrength: 65, valueForMoney: 100 },
    recurring: false, recurringNote: null
  },
  {
    id: 21,
    date: '2026-05-30', dateEnd: '2026-05-30', dateStr: 'Sat May 30',
    title: 'Strawberry Picking',
    subtitle: 'Jaemor Farms — committed family outing',
    venue: 'Jaemor Farms', address: '5340 Cornelia Hwy, Alto, GA',
    lat: 34.4800, lng: -83.6700,
    score: 68, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Outdoor', 'farm', 'seasonal'],
    environment: 'outdoor', eventType: 'park', age: 'All ages',
    time: 'Morning', timeSlot: 'morning', distance: 'road-trip',
    urgent: false, urgentNote: 'Peak strawberry season — goes fast in late May',
    ticketUrl: null, free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/strawberry_picking.jpg', officialUrl: 'https://jaemorfarms.com', instagramUrl: null,
    note: 'Pick-your-own strawberries at the foot of the mountains. Dean will lose his mind. Pair with a mountain drive and lunch stop. Late May = peak season.',
    scoreReasoning: { genreMatch: 30, venueQuality: 58, formatRarity: 72, lineupStrength: 25, valueForMoney: 88 },
    recurring: false, recurringNote: null
  },
  {
    id: 11,
    date: '2026-05-31', dateEnd: '2026-05-31', dateStr: 'Sun May 31',
    title: 'Atlanta Streets Alive',
    subtitle: 'West End to Grant Park',
    venue: 'Atlanta City Streets', address: 'West End, Atlanta, GA',
    lat: 33.7347, lng: -84.4186,
    score: 68, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Outdoor', 'bikes', 'free'],
    environment: 'outdoor', eventType: 'recurring', age: 'All ages',
    time: 'Morning', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.atlstreetsalive.com', free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/atlanta_streets_alive.jpg', officialUrl: 'https://www.atlstreetsalive.com', instagramUrl: null,
    note: 'Car-free streets for bikes, strollers, and pedestrians. West End to Grant Park route. Also runs Jun 14, Sep 27, Oct 18, Nov 8.',
    scoreReasoning: { genreMatch: 30, venueQuality: 72, formatRarity: 65, lineupStrength: 20, valueForMoney: 100 },
    recurring: true, recurringNote: 'Also: Jun 14, Sep 27, Oct 18, Nov 8'
  },
  {
    id: 22,
    date: '2026-06-05', dateEnd: '2026-06-05', dateStr: 'Fri Jun 5',
    title: 'Fernbank After Dark',
    subtitle: 'Adults-only science night · cocktails + demos',
    venue: 'Fernbank Museum', address: '767 Clifton Rd NE, Atlanta, GA',
    lat: 33.7813, lng: -84.3227,
    score: 72, tier: 'B',
    slots: ['DATE_NIGHT'],
    category: 'date', genres: ['Museum', 'cocktails', 'live music', 'adults-only'],
    environment: 'indoor', eventType: 'recurring', age: '21+',
    time: '6 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.fernbankmuseum.org/visit/get-tickets/', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: '6–10 PM',
    youtubeId: null,
    imageUrl: 'images/fernbank_after_dark.jpg', officialUrl: 'https://fernbankmuseum.org', instagramUrl: null,
    note: 'Adults-only science night at Fernbank. Themed cocktails, live music, hands-on demos, and the giant atrium to yourselves. Monthly Fridays. Jeannie will love it.',
    scoreReasoning: { genreMatch: 45, venueQuality: 78, formatRarity: 75, lineupStrength: 55, valueForMoney: 82 },
    recurring: true, recurringNote: 'Monthly Fridays — check fernbankmuseum.org for dates'
  },
  {
    id: 23,
    date: '2026-06-14', dateEnd: '2026-06-14', dateStr: 'Sun Jun 14',
    title: 'Atlanta Streets Alive',
    subtitle: 'FIFA Edition · Beltline route',
    venue: 'Atlanta Beltline', address: 'Atlanta, GA',
    lat: 33.7540, lng: -84.3580,
    score: 65, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Outdoor', 'bikes', 'free'],
    environment: 'outdoor', eventType: 'recurring', age: 'All ages',
    time: 'Morning', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://atlstreetsalive.com', free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: null, officialUrl: 'https://atlstreetsalive.com', instagramUrl: null,
    note: 'FIFA World Cup edition of Streets Alive. Car-free Beltline with bikes and strollers. Dean will have a blast on his bike.',
    scoreReasoning: { genreMatch: 28, venueQuality: 70, formatRarity: 60, lineupStrength: 18, valueForMoney: 100 },
    recurring: false, recurringNote: null
  },
  {
    id: 24,
    date: '2026-06-20', dateEnd: '2026-06-20', dateStr: 'Sat Jun 20',
    title: 'Chattahoochee Tubing',
    subtitle: 'Cool off — group float down the Hooch',
    venue: 'Cool River Tubing', address: '8760 Roswell Rd, Sandy Springs, GA',
    lat: 33.9383, lng: -84.3716,
    score: 72, tier: 'B',
    slots: ['GROUP_NIGHT'],
    category: 'outdoor', genres: ['Outdoor', 'river', 'group'],
    environment: 'outdoor', eventType: 'park', age: 'All ages',
    time: 'Afternoon', timeSlot: 'afternoon', distance: 'OTP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://fareharbor.com/embeds/book/coolrivertubingcompany/?full-items=yes', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/chattahoochee_tubing.png', officialUrl: 'https://coolrivertubing.com', instagramUrl: null,
    note: 'Classic ATL summer tradition. Float the Chattahoochee in tubes. Perfect June group activity before the July heat peaks. BYOB, cash bar, great social format.',
    scoreReasoning: { genreMatch: 35, venueQuality: 68, formatRarity: 70, lineupStrength: 30, valueForMoney: 82 },
    recurring: false, recurringNote: null
  },
  {
    id: 25,
    date: '2026-07-04', dateEnd: '2026-07-04', dateStr: 'Sat Jul 4',
    title: 'Peachtree Road Race',
    subtitle: '10K · World\'s largest road race',
    venue: 'Peachtree Street', address: 'Buckhead to Piedmont Park, Atlanta, GA',
    lat: 33.8360, lng: -84.3852,
    score: 62, tier: 'B',
    slots: ['FAMILY_OUT', 'SOLO_RESET'],
    category: 'outdoor', genres: ['Running', 'outdoor', 'free', 'July 4'],
    environment: 'outdoor', eventType: 'recurring', age: 'All ages',
    time: '7:30 AM', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: 'Registration fills within hours of opening — watch Atlanta Track Club',
    ticketUrl: 'https://landing.letsdothis.com/2026-northsideprr-registration', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: null, officialUrl: 'https://peachtreeroadrace.org', instagramUrl: null,
    note: '60,000 runners. Buckhead to Piedmont Park. World\'s largest 10K. Register early — sells out in hours. Great spectating even if you don\'t run.',
    scoreReasoning: { genreMatch: 28, venueQuality: 72, formatRarity: 68, lineupStrength: 40, valueForMoney: 78 },
    recurring: true, recurringNote: 'Annual July 4th tradition'
  },
  {
    id: 26,
    date: '2026-07-11', dateEnd: '2026-07-11', dateStr: 'Sat Jul 11',
    title: 'ABG Summer Nights',
    subtitle: 'Evening garden access · cocktails + live music',
    venue: 'Atlanta Botanical Garden', address: '1345 Piedmont Ave NE, Atlanta, GA',
    lat: 33.7904, lng: -84.3730,
    score: 68, tier: 'B',
    slots: ['DATE_NIGHT'],
    category: 'date', genres: ['Garden', 'cocktails', 'outdoor evening'],
    environment: 'outdoor', eventType: 'recurring', age: 'All ages',
    time: '6 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://atlantabg.org/tickets/', free: false,
    membershipIncluded: true, membershipVenue: 'ABG',
    advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/abg_summer_nights.jpg', officialUrl: 'https://atlantabg.org', instagramUrl: null,
    note: 'Summer evening extension at ABG. Member access. Garden glows at dusk. Cocktails in the conservatory. Quiet, gorgeous, zero planning required.',
    scoreReasoning: { genreMatch: 35, venueQuality: 88, formatRarity: 65, lineupStrength: 40, valueForMoney: 90 },
    recurring: true, recurringNote: 'Summer Thursdays + select Saturdays — check atlantabg.org'
  },
  {
    id: 27,
    date: '2026-09-13', dateEnd: '2026-09-13', dateStr: 'Sun Sep 13',
    title: 'Empire of the Sun',
    subtitle: 'Ask That God: Afterlife North American Tour',
    venue: 'Ameris Bank Amphitheatre', address: '2200 Encore Pkwy, Alpharetta, GA',
    lat: 34.0738, lng: -84.2783,
    score: 75, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Electronic pop', 'art-rock', 'psychedelic'],
    environment: 'outdoor', eventType: 'live', age: 'All ages',
    time: '7:30 PM', timeSlot: 'evening', distance: 'OTP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://www.ticketmaster.com/empire-of-the-sun-ask-that-alpharetta-georgia-09-13-2026/event/0E006466AAAEAAE3', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: ['Empire of the Sun'],
    setTimes: null,
    youtubeId: 'y6qigQlIFB4',
    imageUrl: 'images/empire_of_the_sun.jpg', officialUrl: 'https://www.livenation.com/event/vvG1zZ_kQnlnlN/empire-of-the-sun-ask-that-god-afterlife-north-american-tour', instagramUrl: 'https://instagram.com/empireofthesunmusic',
    note: 'Empire of the Sun on the "Ask That God" North American tour — all the theatrical costuming, celestial visuals, and arena-scale production you expect. Luke Steele performing Walking on a Dream, We Are the People, High and Low under the stars at Ameris Bank Amphitheatre. This is a great September group show — weather has cooled, outdoors in Alpharetta, bring whoever wants a spectacle. It\'s not the highest scoring night of the season but the atmosphere is unmatched for what it is. Coordinate 3–4 weeks early for the drive-up crew.',
    scoreReasoning: { genreMatch: 80, venueQuality: 55, formatRarity: 72, lineupStrength: 82, valueForMoney: 65 },
    recurring: false, recurringNote: null
  },
  {
    id: 28,
    date: '2026-09-18', dateEnd: '2026-09-20', dateStr: 'Fri–Sun Sep 18–20',
    title: 'Shaky Knees 2026',
    subtitle: 'Gorillaz · LCD Soundsystem · Wu-Tang · The Strokes',
    venue: 'Piedmont Park', address: 'Piedmont Park, Atlanta, GA',
    lat: 33.7869, lng: -84.3734,
    score: 80, tier: 'A',
    slots: ['GROUP_NIGHT'],
    category: 'music', genres: ['Multi-genre festival', 'rock', 'hip-hop'],
    environment: 'outdoor', eventType: 'festival', age: 'All ages',
    time: 'All weekend', timeSlot: 'allday', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://shakykneesmusic.com', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: ['Gorillaz', 'LCD Soundsystem', 'Wu-Tang Clan', 'The Strokes', 'Twenty One Pilots', 'The Prodigy', 'Blood Orange'],
    setTimes: 'Fri: The Strokes · Sat: Twenty One Pilots · Sun: Gorillaz',
    youtubeId: null,
    imageUrl: 'images/shaky_knees_2026.png', officialUrl: 'https://shakykneesmusic.com', instagramUrl: 'https://instagram.com/shakykneesmusic',
    note: 'Shaky Knees 2026 is stacked across all three days at Piedmont Park. Friday: The Strokes headline with LCD Soundsystem co-headlining — arguably the greatest indie-rock double bill of the year. Saturday: Twenty One Pilots and The Prodigy (UK rave legends, Blood Orange supporting). Sunday: Gorillaz closing the weekend with their full live band and visual production — expect Clint Eastwood, DARE, Feel Good Inc. Wu-Tang Clan also on the bill. 3-day pass gives the most flexibility; single days available too. Piedmont Park keeps it walkable from the neighborhood. Plan this early — it will sell.',
    scoreReasoning: { genreMatch: 72, venueQuality: 75, formatRarity: 68, lineupStrength: 92, valueForMoney: 72 },
    recurring: false, recurringNote: null
  },
  {
    id: 29,
    date: '2026-09-27', dateEnd: '2026-09-27', dateStr: 'Sun Sep 27',
    title: 'Atlanta Streets Alive',
    subtitle: 'Peachtree Street route',
    venue: 'Peachtree Street', address: 'Peachtree St, Atlanta, GA',
    lat: 33.7728, lng: -84.3860,
    score: 65, tier: 'B',
    slots: ['FAMILY_OUT'],
    category: 'family', genres: ['Outdoor', 'bikes', 'free'],
    environment: 'outdoor', eventType: 'recurring', age: 'All ages',
    time: 'Morning', timeSlot: 'morning', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://atlstreetsalive.com', free: true,
    membershipIncluded: false, membershipVenue: null, advancePurchase: false,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: null, officialUrl: 'https://atlstreetsalive.com', instagramUrl: null,
    note: 'Peachtree Street car-free. One of the most scenic Streets Alive routes. Fall weather makes it even better.',
    scoreReasoning: { genreMatch: 28, venueQuality: 72, formatRarity: 58, lineupStrength: 18, valueForMoney: 100 },
    recurring: false, recurringNote: null
  },
  {
    id: 30,
    date: '2026-05-02', dateEnd: '2026-05-02', dateStr: 'Sat May 2',
    title: 'Dad\'s Garage: ROAD TRIP!',
    subtitle: 'Long-form improv · action movie night',
    venue: 'Dad\'s Garage Theatre', address: '569 Ezzard St SE, Atlanta, GA',
    lat: 33.7349, lng: -84.3635,
    score: 66, tier: 'B',
    slots: ['GROUP_NIGHT'],
    category: 'comedy', genres: ['Improv', 'long-form', 'action comedy'],
    environment: 'indoor', eventType: 'live', age: 'All ages',
    time: '8 PM', timeSlot: 'evening', distance: 'ITP',
    urgent: false, urgentNote: null,
    ticketUrl: 'https://dadsgarage.my.salesforce-sites.com/ticket/PatronTicket__PublicTicketApp', free: false,
    membershipIncluded: false, membershipVenue: null, advancePurchase: true,
    lineup: [],
    setTimes: null,
    youtubeId: null,
    imageUrl: 'images/dad_s_garage_road_trip.png', officialUrl: 'https://dadsgarage.com', instagramUrl: 'https://instagram.com/dadsgarage',
    note: 'Dad\'s Garage signature long-form improv. ROAD TRIP! is their action-movie parody format — genre-based improv at its best. Multiple dates available. Coordinate with your crew.',
    scoreReasoning: { genreMatch: 40, venueQuality: 65, formatRarity: 75, lineupStrength: 55, valueForMoney: 80 },
    recurring: true, recurringNote: 'Runs Fri–Sat most weekends — check dadsgarage.com for schedule'
  }
];

// ─── EVERGREEN ACTIVITIES ──────────────────────────────────────────────────

const EVERGREEN = [
  // ── FAMILY / WITH DEAN ──────────────────────────────────────────────────
  {
    id: 'e01', name: 'Atlanta Botanical Garden', emoji: '🌿',
    category: 'family', description: 'Sensory trail, Japanese garden, seasonal canopy walk. ABG member — walk in any time. Great for toddlers.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: true, membershipVenue: 'ABG',
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 4, parentScore: 5,
    address: '1345 Piedmont Ave NE, Atlanta, GA', lat: 33.7904, lng: -84.3730,
    url: 'https://atlantabg.org', notes: 'Member. Go early AM on weekdays for quiet hours.'
  },
  {
    id: 'e02', name: 'Fernbank Museum', emoji: '🦕',
    category: 'family', description: 'Dinosaur hall with full-size T-Rex skeleton. Dean is obsessed. Giant diorama lobby. Perfect rainy day.',
    effort: 'low', distance: 'ITP', timeOfDay: 'anytime', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: false, cost: 'Member', membershipIncluded: true, membershipVenue: 'Fernbank',
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 4,
    address: '767 Clifton Rd NE, Atlanta, GA', lat: 33.7813, lng: -84.3227,
    url: 'https://fernbankmuseum.org', notes: 'Member. Rainy day default. Dean could go weekly.'
  },
  {
    id: 'e03', name: 'Zoo Atlanta', emoji: '🦒',
    category: 'family', description: 'Giant pandas, gorillas, African Savanna. Zoo member. Best on weekday mornings before crowds.',
    effort: 'medium', distance: 'ITP', timeOfDay: 'morning', bestDays: 'weekday',
    duration: '2hr', groupSize: 'family',
    free: false, cost: 'Member', membershipIncluded: true, membershipVenue: 'Zoo',
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 4,
    address: '800 Cherokee Ave SE, Atlanta, GA', lat: 33.7349, lng: -84.3717,
    url: 'https://zooatlanta.org', notes: 'Member. Go early morning. Skip weekends in summer.'
  },
  {
    id: 'e04', name: 'Atlanta History Center', emoji: '🏛️',
    category: 'family', description: 'Swan House mansion, Civil War gallery, Swan Coach House garden. Member access. Good for a slower cultural morning.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: false, cost: 'Member', membershipIncluded: true, membershipVenue: 'AHC',
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 3, parentScore: 4,
    address: '130 West Paces Ferry Rd NW, Atlanta, GA', lat: 33.8383, lng: -84.3866,
    url: 'https://atlantahistorycenter.com', notes: 'Member. Best for slower, more reflective family outings.'
  },
  {
    id: 'e05', name: 'Beltline + Krog Street Market', emoji: '🚲',
    category: 'family', description: 'Stroller on the trail, snack stop at Krog. Easy afternoon out — Dean loves the "train ride" on the path.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'afternoon', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 4, parentScore: 4,
    address: 'Krog Street Market, 99 Krog St NE, Atlanta, GA', lat: 33.7540, lng: -84.3590,
    url: null, notes: 'Free. Zero planning required. Walk to Beltline from home in 20 min.'
  },
  {
    id: 'e06', name: 'Chattahoochee Nature Center', emoji: '🦅',
    category: 'family', description: 'Wildlife rehab encounters, raptors, easy boardwalks. Educational without being intense. A quiet escape.',
    effort: 'low', distance: 'OTP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: false, cost: '$10–15', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 4, parentScore: 4,
    address: '9135 Willeo Rd, Roswell, GA', lat: 33.9477, lng: -84.4669,
    url: 'https://chattnaturecenter.org', notes: 'Great for a half-day trip north of the city.'
  },
  {
    id: 'e07', name: 'Children\'s Museum of Atlanta', emoji: '🧩',
    category: 'family', description: 'Indoor toddler-focused play. Water table, building zone, art studio. Rainy day essential.',
    effort: 'low', distance: 'ITP', timeOfDay: 'anytime', bestDays: 'weekday',
    duration: '2hr', groupSize: 'family',
    free: false, cost: '$18', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: true, rubyFriendly: false,
    deanScore: 5, parentScore: 3,
    address: '275 Centennial Olympic Park Dr NW, Atlanta, GA', lat: 33.7613, lng: -84.3867,
    url: 'https://childrensmuseumatlanta.org', notes: 'Rainy day. Dean will go full chaos mode in the water table.'
  },
  {
    id: 'e08', name: 'Sloomoo Institute', emoji: '🌈',
    category: 'family', description: 'High-sensory slime experience. Color, texture, light. Dean would be absolutely losing it — in the best way.',
    effort: 'low', distance: 'ITP', timeOfDay: 'anytime', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: false, cost: '$32', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 5, parentScore: 3,
    address: '990 Marietta St NW, Atlanta, GA', lat: 33.7900, lng: -84.3840,
    url: 'https://sloomooinstitute.com/atlanta', notes: 'Advance tickets. Toddler-specific slots available.'
  },
  {
    id: 'e09', name: 'LEGO Discovery Center', emoji: '🧱',
    category: 'family', description: 'Indoor LEGO heaven. Build stations, 4D cinema, Miniland ATL. Best rainy day option for 3-7yo.',
    effort: 'low', distance: 'OTP', timeOfDay: 'anytime', bestDays: 'any',
    duration: 'half-day', groupSize: 'family',
    free: false, cost: '$25+', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 5, parentScore: 3,
    address: '3500 Peachtree Rd NE, Atlanta, GA', lat: 33.8600, lng: -84.3570,
    url: 'https://legodiscoverycenter.com/atlanta', notes: 'Book online. Worth the trip on a bad weather weekend.'
  },
  {
    id: 'e27', name: 'Georgia Aquarium', emoji: '🐋',
    category: 'family', description: 'World\'s largest aquarium. Whale sharks, beluga whales, manta rays. Dean will be glued to the glass.',
    effort: 'medium', distance: 'ITP', timeOfDay: 'morning', bestDays: 'weekday',
    duration: 'half-day', groupSize: 'family',
    free: false, cost: '$35–45', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 5,
    address: '225 Baker St NW, Atlanta, GA', lat: 33.7631, lng: -84.3950,
    url: 'https://georgiaaquarium.org', notes: 'Book tickets online. Go weekday morning to avoid crowds. Whale shark tank alone is worth the trip.'
  },
  {
    id: 'e28', name: 'Centennial Olympic Park Splash Pad', emoji: '⛲',
    category: 'family', description: 'Free Olympic rings fountain. Dean chases the jets. Downtown landmark with space to run. Works great before or after aquarium.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 4,
    address: '265 Park Ave W NW, Atlanta, GA', lat: 33.7607, lng: -84.3921,
    url: null, notes: 'Free. Splash pad open late spring through summer. Bring a change of clothes.'
  },
  {
    id: 'e29', name: 'MLK National Historic Site', emoji: '✊',
    category: 'family', description: 'Free national park. MLK\'s birth home, Ebenezer Baptist Church, Freedom Hall. Quiet and profound.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 3, parentScore: 5,
    address: '450 Auburn Ave NE, Atlanta, GA', lat: 33.7552, lng: -84.3713,
    url: 'https://nps.gov/malu', notes: 'Free. Birth home tours free but capacity-limited — arrive early.'
  },
  {
    id: 'e30', name: 'Arabia Mountain Trail', emoji: '🪨',
    category: 'family', description: 'Granite dome hiking 30 min from VaHi. Exposed rock formations, wildflowers, views. Dean can do the summit.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 4, parentScore: 5,
    address: 'Arabia Mountain National Heritage Area, Lithonia, GA', lat: 33.6706, lng: -84.0964,
    url: 'https://arabiaalliance.org', notes: 'Go early morning in spring. Bring water and trail shoes. Wildflowers are incredible March–May.'
  },
  {
    id: 'e31', name: 'Sweetwater Creek State Park', emoji: '🌊',
    category: 'family', description: 'Easy trail to historic ruins at the water\'s edge. Stunning creek views, shallow wading spots. Dean loves the water.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: false, cost: '$5 parking', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 4, parentScore: 5,
    address: '1750 Mt Vernon Rd, Lithia Springs, GA', lat: 33.7715, lng: -84.6304,
    url: null, notes: '$5 parking pass. Factory ruins loop is 2.2 miles and manageable with a carrier.'
  },
  {
    id: 'e32', name: 'Center for Puppetry Arts', emoji: '🎭',
    category: 'family', description: 'World-class puppet theater + hands-on museum. Jim Henson collection on display. Dean will be captivated.',
    effort: 'low', distance: 'ITP', timeOfDay: 'afternoon', bestDays: 'weekend',
    duration: '2hr', groupSize: 'family',
    free: false, cost: '$14–20', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: true, rubyFriendly: false,
    deanScore: 5, parentScore: 4,
    address: '1404 Spring St NW, Atlanta, GA', lat: 33.7929, lng: -84.3855,
    url: 'https://puppet.org', notes: 'Book the matinee. Interactive build-a-puppet workshop available.'
  },
  {
    id: 'e33', name: 'Kennesaw Mountain Hike', emoji: '⛰️',
    category: 'family', description: 'Civil War battlefield with summit hike. Views over the city. Easy to moderate trail. Great family half-day.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 3, parentScore: 5,
    address: '900 Kennesaw Mountain Dr, Kennesaw, GA', lat: 33.9696, lng: -84.5801,
    url: 'https://nps.gov/kemo', notes: 'Free. Drive summit road or hike to top (2.2 miles). Go early in summer.'
  },
  {
    id: 'e34', name: 'PDK Airport Plane Watching', emoji: '✈️',
    category: 'family', description: 'Watch private planes and helicopters land from the fence at DeKalb-Peachtree Airport. Dean is obsessed with planes.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '30min', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 4,
    address: 'PDK Airport, 1997 Airport Rd, Chamblee, GA', lat: 33.8754, lng: -84.3021,
    url: null, notes: 'Park on Clairmont Rd side. Jets + props taking off every few minutes. 30 min of pure Dean magic.'
  },
  {
    id: 'e35', name: 'Freedom Park Trail', emoji: '🌳',
    category: 'family', description: 'Flat 3-mile trail from Ponce City Market through Inman Park. Murals, greenway, playground stops. Zero friction.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 4, parentScore: 4,
    address: 'Freedom Park, Atlanta, GA', lat: 33.7640, lng: -84.3540,
    url: null, notes: 'Connect to Carter Center and Inman Park. Flat enough for a stroller run.'
  },

  // ── PAPA + DEAN ──────────────────────────────────────────────────────────
  {
    id: 'e10', name: 'Car Wash (Tunnel)', emoji: '🚗',
    category: 'papa', description: "Dean is OBSESSED with the tunnel car wash. Papa drives, Dean loses his mind. Zero planning. Maximum Dean joy.",
    effort: 'low', distance: 'neighborhood', timeOfDay: 'morning', bestDays: 'any',
    duration: '30min', groupSize: 'family',
    free: false, cost: '$15', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 5,
    address: 'Various — neighborhood', lat: 33.7843, lng: -84.3601,
    url: null, notes: 'Pure joy activation. Follow with donuts for maximum effect.'
  },
  {
    id: 'e11', name: 'Morningside Library + Donuts', emoji: '📚',
    category: 'papa', description: "Papa storytime at Morningside Branch. Then Revolution Donuts around the corner. Dean's favorite morning loop.",
    effort: 'low', distance: 'neighborhood', timeOfDay: 'morning', bestDays: 'weekday',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: false,
    deanScore: 4, parentScore: 5,
    address: '1117 Johnson Rd NE, Atlanta, GA', lat: 33.7968, lng: -84.3477,
    url: null, notes: 'Not Sundays. Morning/afternoon only. Check storytime schedule.'
  },
  {
    id: 'e12', name: 'Neighborhood Playground Run', emoji: '🛝',
    category: 'papa', description: 'Sydney Marcus, Noble Park, or Old Fourth Ward. Papa + Dean playground circuit. Zero friction, pure output.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 4, parentScore: 5,
    address: 'Virginia-Highland / 30306', lat: 33.7843, lng: -84.3601,
    url: null, notes: 'Rotate: Sydney Marcus → Noble Park → OFW Park → Orme Park.'
  },
  {
    id: 'e36', name: 'Chick-fil-A + Playground', emoji: '🐔',
    category: 'papa', description: 'Nuggets + indoor play structure. Dean knows what Chick-fil-A is and will lose it. Zero prep. Local, fast, high joy return.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: false, cost: '$10', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: false,
    deanScore: 5, parentScore: 4,
    address: 'Various CFA locations', lat: 33.7843, lng: -84.3601,
    url: null, notes: 'Go off-peak (10–11 AM or 2–4 PM) to avoid lunch rush. Indoor play structure available at most locations.'
  },
  {
    id: 'e37', name: 'DeKalb Farmers Market', emoji: '🥭',
    category: 'papa', description: 'International farmers market. Free samples, exotic fruits, the chaos. Dean loves sampling. Papa gets groceries done.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 3, parentScore: 5,
    address: '3000 E Ponce de Leon Ave, Decatur, GA', lat: 33.7742, lng: -84.2963,
    url: 'https://dekalbfarmersmarket.com', notes: 'Go weekday morning. Free mango samples. No phone inside.'
  },
  {
    id: 'e38', name: 'Trains at Centennial Park', emoji: '🚂',
    category: 'papa', description: 'Miniature train rides at Centennial Olympic Park. Dean + trains = 100% success rate. Easy park access.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'family',
    free: false, cost: '$4 ride', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: true, rubyFriendly: true,
    deanScore: 5, parentScore: 4,
    address: 'Centennial Olympic Park, Atlanta, GA', lat: 33.7607, lng: -84.3921,
    url: null, notes: 'Check seasonal operation. Combine with splash pad next door for a full morning.'
  },

  // ── SOLO RESET ────────────────────────────────────────────────────────────
  {
    id: 'e13', name: 'Sol Dance (Ecstatic Dance)', emoji: '💃',
    category: 'solo', description: 'Non-verbal connection, high energy movement, sober or not. 2nd Sunday monthly at Brook Run Park, Dunwoody. Physical reset without gym equipment.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'afternoon', bestDays: 'weekend',
    duration: '2hr', groupSize: 'solo',
    free: false, cost: '$15–20', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: 'Brook Run Park, 4770 N Peachtree Rd, Dunwoody, GA', lat: 33.9572, lng: -84.3379,
    url: 'https://soldancemovement.com', notes: '2nd Sunday monthly, 12–4 PM. No phones, no alcohol required.'
  },
  {
    id: 'e14', name: 'Five Rhythms', emoji: '🌊',
    category: 'solo', description: 'Conscious movement practice. Sundays 4–6 PM + Friday evenings. Meditative physical reset.',
    effort: 'medium', distance: 'ITP', timeOfDay: 'afternoon', bestDays: 'any',
    duration: '2hr', groupSize: 'solo',
    free: false, cost: '$15–20', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '465 Boulevard SE, Atlanta, GA', lat: 33.7397, lng: -84.3706,
    url: 'https://juliestuart5rhythms.com', notes: 'Sundays 4–6 PM + Fridays. No experience needed.'
  },
  {
    id: 'e15', name: 'ABG Quiet Hours (Early AM)', emoji: '☀️',
    category: 'solo', description: 'Early member access to the Japanese Garden before crowds. Meditative. The city doesn\'t exist yet.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'weekday',
    duration: '1hr', groupSize: 'solo',
    free: true, cost: null, membershipIncluded: true, membershipVenue: 'ABG',
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 5,
    address: '1345 Piedmont Ave NE, Atlanta, GA', lat: 33.7904, lng: -84.3730,
    url: null, notes: 'Member perk. Best 7–9 AM on weekdays. Japanese Garden is the destination.'
  },
  {
    id: 'e16', name: 'High Museum — Second Sundays', emoji: '🎨',
    category: 'solo', description: 'Free community admission. Best enjoyed solo for quiet immersion through the galleries. Monthly ritual.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'weekend',
    duration: '2hr', groupSize: 'solo',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 5,
    address: '1280 Peachtree St NE, Atlanta, GA', lat: 33.7902, lng: -84.3853,
    url: 'https://high.org', notes: 'Second Sunday of each month. Free. Go early to beat the crowd.'
  },
  {
    id: 'e39', name: 'Oakland Cemetery Morning Walk', emoji: '🌺',
    category: 'solo', description: 'Victorian garden cemetery with stunning architecture, Margaret Mitchell\'s grave, and total quiet. Stunning in spring.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'solo',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 5,
    address: '248 Oakland Ave SE, Atlanta, GA', lat: 33.7490, lng: -84.3700,
    url: 'https://oaklandcemetery.com', notes: 'Free entry. Best on a weekday morning. Seasonal gardens are exceptional.'
  },
  {
    id: 'e40', name: 'Emory Carlos Museum', emoji: '🏺',
    category: 'solo', description: 'Small, quiet world-class collection. Egyptian mummies, Greek antiquities, Sub-Saharan art. Often empty. The antidote to High Museum crowds.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'weekday',
    duration: '1hr', groupSize: 'solo',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 5,
    address: '571 S Kilgo Cir, Atlanta, GA', lat: 33.7948, lng: -84.3222,
    url: 'https://carlos.emory.edu', notes: 'Free. Closed Monday. Often quiet on weekday mornings. Meditative experience.'
  },
  {
    id: 'e41', name: 'Stone Summit Climbing', emoji: '🧗',
    category: 'solo', description: 'Indoor rock climbing. Physical reset, focused, meditative. Go early morning for quiet walls.',
    effort: 'high', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'solo',
    free: false, cost: '$22', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '3820 Greenbriar Pkwy SW, Atlanta, GA', lat: 33.7273, lng: -84.4700,
    url: 'https://stonesummit.com', notes: 'Best early weekday morning. Rentals available.'
  },
  {
    id: 'e42', name: 'Piedmont Park Early Run', emoji: '🏃',
    category: 'solo', description: 'The city\'s front yard. 3-mile loop around the park. Weekend mornings have farmer\'s market. Perfect solo reset.',
    effort: 'medium', distance: 'neighborhood', timeOfDay: 'morning', bestDays: 'any',
    duration: '1hr', groupSize: 'solo',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 3, parentScore: 4,
    address: 'Piedmont Park, Atlanta, GA', lat: 33.7869, lng: -84.3734,
    url: null, notes: 'Saturday morning = Green Market. Sunday = quieter for running. Park opens at 6 AM.'
  },

  // ── DATE NIGHT ────────────────────────────────────────────────────────────
  {
    id: 'e17', name: 'Bacchanalia', emoji: '🍽️',
    category: 'date', description: "ATL's flagship fine dining. Prix-fixe. Book 2+ weeks out. Special occasions only — worth every penny.",
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '1198 Howell Mill Rd NW, Atlanta, GA', lat: 33.7951, lng: -84.4105,
    url: 'https://starprovisions.com/restaurants/bacchanalia', notes: 'Book 2+ weeks ahead. The best table in Atlanta.'
  },
  {
    id: 'e18', name: 'Little Bear', emoji: '🐻',
    category: 'date', description: 'Beltline fine-casual. Fresh, seasonal, intimate. 1-week reservation window. Perfect for a weeknight reset.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '61 Krog St NE, Atlanta, GA', lat: 33.7521, lng: -84.3598,
    url: null, notes: 'Book 1 week out on OpenTable. Weeknights easier than weekends.'
  },
  {
    id: 'e19', name: 'Fox Theatre', emoji: '🎭',
    category: 'date', description: 'Broadway touring productions in Atlanta\'s most spectacular venue. Book when the right show lands.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$$–$$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '660 Peachtree St NE, Atlanta, GA', lat: 33.7728, lng: -84.3860,
    url: 'https://foxtheatre.org', notes: 'Best for a special occasion — book when the right tour comes through.'
  },
  {
    id: 'e20', name: 'Fernbank After Dark', emoji: '🔭',
    category: 'date', description: 'Adults-only science night at Fernbank. Cocktails, live music, hands-on demos after hours. Monthly Friday.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$20', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '767 Clifton Rd NE, Atlanta, GA', lat: 33.7813, lng: -84.3227,
    url: 'https://fernbankmuseum.org', notes: 'Monthly Friday evenings. 21+. Jeannie would love this.'
  },
  {
    id: 'e21', name: 'Ponce City Market Rooftop', emoji: '🎡',
    category: 'date', description: 'Mini golf, cocktails, skyline views, carnival rides. Easy date, low planning, high payoff.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '1hr', groupSize: 'couple',
    free: false, cost: '$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 3, parentScore: 4,
    address: '675 Ponce De Leon Ave NE, Atlanta, GA', lat: 33.7723, lng: -84.3632,
    url: null, notes: 'No reservation. Easy walk-up. Views are worth it even without the rides.'
  },
  {
    id: 'e43', name: 'Tiny Lou\'s', emoji: '🍸',
    category: 'date', description: 'Jazz bar in Hotel Clermont. Cabaret atmosphere, craft cocktails, live jazz Wednesday–Saturday. Old Atlanta energy.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '789 Ponce De Leon Ave NE, Atlanta, GA', lat: 33.7713, lng: -84.3498,
    url: 'https://tinylousatl.com', notes: 'Walk-in or reservation. Order the negroni. Live jazz nights are special.'
  },
  {
    id: 'e44', name: 'Ladybird Grove & Mess Hall', emoji: '🌿',
    category: 'date', description: 'Beltline patio bar with Piedmont Park views. Outdoor string lights, cocktails, casual bites. Zero pretension, maximum vibe.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '1hr', groupSize: 'couple',
    free: false, cost: '$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 4,
    address: '684 John Lewis Freedom Pkwy NE, Atlanta, GA', lat: 33.7745, lng: -84.3610,
    url: 'https://ladybirdatl.com', notes: 'Walk-up only. Go before sunset for the golden hour views. Cash or card.'
  },
  {
    id: 'e45', name: 'Sun in My Belly', emoji: '🥞',
    category: 'date', description: 'Reynoldstown breakfast/brunch gem. Outdoor patio, communal vibe, exceptional coffee. The best Saturday morning date format.',
    effort: 'low', distance: 'ITP', timeOfDay: 'morning', bestDays: 'weekend',
    duration: '1hr', groupSize: 'couple',
    free: false, cost: '$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 4,
    address: '2161 College Ave NE, Atlanta, GA', lat: 33.7495, lng: -84.3470,
    url: 'https://suninmybelly.com', notes: 'Walk-in on weekdays. Small wait on weekends — worth it.'
  },
  {
    id: 'e46', name: 'Alliance Theatre', emoji: '🎭',
    category: 'date', description: 'ATL\'s premier regional theater. World premieres, Broadway transfers, consistent quality. Book around a show you both want.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '1280 Peachtree St NE, Atlanta, GA', lat: 33.7902, lng: -84.3853,
    url: 'https://alliancetheatre.org', notes: 'Book 1–2 weeks out. Often does dinner + show packages with nearby restaurants.'
  },
  {
    id: 'e47', name: 'Eddie\'s Attic', emoji: '🎸',
    category: 'date', description: 'Legendary listening room in Decatur. Intimate acoustic sets, no bad seats. Where John Mayer got his start. Reserve the balcony.',
    effort: 'low', distance: 'OTP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'couple',
    free: false, cost: '$15–30', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '515 N McDonough St, Decatur, GA', lat: 33.7748, lng: -84.2963,
    url: 'https://eddiesattic.com', notes: 'Check calendar for shows. Balcony table is worth the reservation fee.'
  },

  // ── GROUP / SOCIAL ────────────────────────────────────────────────────────
  {
    id: 'e22', name: "Ormsby's", emoji: '🎯',
    category: 'group', description: 'Billiards, bocce, shuffleboard. West Midtown. Perfect group format — parallel socializing with games.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '1170 Howell Mill Rd NW, Atlanta, GA', lat: 33.7903, lng: -84.4120,
    url: null, notes: 'Great for 6–12 people. No reservation for billiards tables.'
  },
  {
    id: 'e23', name: 'Lake Claire Drum Circle', emoji: '🥁',
    category: 'group', description: 'Full moon celebrations at Lake Claire Land Trust. High community vibe. Bring a drum or just show up.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 3, parentScore: 4,
    address: 'Lake Claire Land Trust, Atlanta, GA', lat: 33.7666, lng: -84.3306,
    url: null, notes: 'Full moon monthly. Free, open, no experience needed.'
  },
  {
    id: 'e24', name: 'Krog Street Market (Evening)', emoji: '🔥',
    category: 'group', description: 'Fire pit patio, outdoor seating, food hall. Oct–Apr fire pit season is best. Easy last-minute neighbor hang.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 4,
    address: '99 Krog St NE, Atlanta, GA', lat: 33.7540, lng: -84.3590,
    url: null, notes: 'Zero planning. Text a few people and go. Works any night.'
  },
  {
    id: 'e25', name: 'Axe Throwing (The Battery)', emoji: '🪓',
    category: 'group', description: 'High social energy. Requires advance booking. Good for birthdays or group bonding. 6–10 person format.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$30+', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: 'The Battery, 800 Battery Ave SE, Atlanta, GA', lat: 33.8906, lng: -84.4683,
    url: null, notes: 'Book ahead. Best for 6–10 people. Good for out-of-town visitors.'
  },
  {
    id: 'e26', name: 'Stone Summit (Rock Climbing)', emoji: '🧗',
    category: 'solo', description: 'Indoor rock climbing. Physical reset, focused, meditative. Go early morning for quiet walls.',
    effort: 'high', distance: 'ITP', timeOfDay: 'morning', bestDays: 'any',
    duration: '2hr', groupSize: 'solo',
    free: false, cost: '$22', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 5,
    address: '3820 Greenbriar Pkwy SW, Atlanta, GA', lat: 33.7273, lng: -84.4700,
    url: 'https://stonesummit.com', notes: 'Best early weekday morning. Rentals available.'
  },
  {
    id: 'e48', name: 'Dad\'s Garage Comedy Night', emoji: '😂',
    category: 'group', description: 'ATL\'s best improv theater. Long-form, short-form, genre nights. Multiple shows weekly. Consistently great group format.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$15–25', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '569 Ezzard St SE, Atlanta, GA', lat: 33.7349, lng: -84.3635,
    url: 'https://dadsgarage.com', notes: 'Check schedule for ROAD TRIP!, Quick & Dirty, and genre nights. Book ahead on weekends.'
  },
  {
    id: 'e49', name: 'Laughing Skull Lounge', emoji: '🎤',
    category: 'group', description: 'Intimate stand-up comedy club in Midtown. National touring acts and local headliners. Two-drink minimum.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$15–25', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '878 Peachtree St NE, Atlanta, GA', lat: 33.7798, lng: -84.3842,
    url: 'https://laughingskulllounge.com', notes: 'Book ahead for good seats. Friday/Saturday shows sell fast.'
  },
  {
    id: 'e50', name: 'Braves Game at Truist Park', emoji: '⚾',
    category: 'group', description: 'Battery Atlanta pregame + Braves. Family-friendly, great food options. Not a passion play but a strong group-night format.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'evening', bestDays: 'any',
    duration: 'half-day', groupSize: 'group',
    free: false, cost: '$25–60', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 3, parentScore: 3,
    address: '755 Battery Ave SE, Marietta, GA', lat: 33.8906, lng: -84.4683,
    url: 'https://mlb.com/braves', notes: 'Battery area pregame is genuinely great. Go for the experience, not baseball specifically.'
  },
  {
    id: 'e51', name: 'Topgolf Midtown', emoji: '⛳',
    category: 'group', description: 'Tech-driven driving range with bay seating. High social energy. Works for groups of all skill levels. Good food + cocktails.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 4,
    address: '1001 Phillip Lee Dr SW, Atlanta, GA', lat: 33.7726, lng: -84.4320,
    url: 'https://topgolf.com/us/atlanta', notes: 'Walk-in ok but wait times can be 1–2 hrs on weekends. Book a bay in advance.'
  },
  {
    id: 'e52', name: 'Painted Pin (Bowling + Games)', emoji: '🎳',
    category: 'group', description: 'Upscale bowling in Buckhead with bar, shuffle puck, and darts. Perfect group format — parallel activities reduce need to coordinate.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 4,
    address: '737 Miami Cir NE, Atlanta, GA', lat: 33.8440, lng: -84.3578,
    url: 'https://paintedpin.com', notes: 'Reserve a lane in advance. Happy hour on weeknights. Good for groups of 6–10.'
  },
  {
    id: 'e53', name: 'Virginia Highland Bar Crawl', emoji: '🍺',
    category: 'group', description: 'Walk the neighborhood — Murphy\'s, Hand in Hand, Neighbors, dark horse. Classic ATL night format. Zero planning required.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: 'Virginia-Highland, Atlanta, GA', lat: 33.7843, lng: -84.3601,
    url: null, notes: 'Start at Murphy\'s. End at Hand in Hand. Zero coordination needed.'
  },
  {
    id: 'e54', name: 'Manuel\'s Tavern Pub Trivia', emoji: '🧠',
    category: 'group', description: 'Atlanta institution. Weekly trivia nights. Great wings, cold drafts, zero pretension. City council members and grad students share the room.',
    effort: 'low', distance: 'ITP', timeOfDay: 'evening', bestDays: 'weekday',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '602 N Highland Ave NE, Atlanta, GA', lat: 33.7693, lng: -84.3543,
    url: null, notes: 'Tuesday trivia nights. Arrive early for seating. $2 trivia entry.'
  },
  {
    id: 'e55', name: 'Chattahoochee River Tubing', emoji: '🛟',
    category: 'group', description: 'Classic ATL summer tradition. Float the Hooch in tubes for 2 hours. Cash bar mid-river. Best Memorial Day through Labor Day.',
    effort: 'medium', distance: 'OTP', timeOfDay: 'afternoon', bestDays: 'weekend',
    duration: '2hr', groupSize: 'group',
    free: false, cost: '$20–25', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 5,
    address: 'Cool River Tubing, 8760 Roswell Rd, Sandy Springs, GA', lat: 33.9383, lng: -84.3716,
    url: 'https://coolrivertubing.com', notes: 'No reservations, first-come. Go early on summer weekends — fills up by noon.'
  },
  {
    id: 'e56', name: 'Red Top Mountain State Park', emoji: '🌲',
    category: 'group', description: 'Lakeside hiking 45 min north. Marina, kayak rentals, easy trails with water views. Great full-day group escape.',
    effort: 'medium', distance: 'road-trip', timeOfDay: 'morning', bestDays: 'any',
    duration: 'half-day', groupSize: 'group',
    free: false, cost: '$5 parking', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 3, parentScore: 5,
    address: '50 Lodge Rd SE, Cartersville, GA', lat: 34.1540, lng: -84.7090,
    url: null, notes: 'Kayak rentals at the marina. 12-mile trail network. Good early summer before heat peaks.'
  },
  {
    id: 'e57', name: 'Beltline ArtWalk (1st Friday)', emoji: '🖼️',
    category: 'group', description: 'Monthly 1st Friday on the Eastside Trail. Pop-up artists, food trucks, the city\'s most eclectic crowd. Free, casual, electric.',
    effort: 'low', distance: 'neighborhood', timeOfDay: 'evening', bestDays: 'any',
    duration: '2hr', groupSize: 'group',
    free: true, cost: null, membershipIncluded: false, membershipVenue: null,
    ticketsRequired: false, papaFriendly: false, rubyFriendly: false,
    deanScore: 2, parentScore: 4,
    address: 'Atlanta Beltline Eastside Trail', lat: 33.7540, lng: -84.3590,
    url: null, notes: '1st Friday monthly. Jun 5, Jul 3, Aug 7, Sep 4. Walk from Krog to Piedmont Park.'
  },
  {
    id: 'e58', name: 'Escape Room (Escapology)', emoji: '🔐',
    category: 'group', description: 'Narrative escape rooms in Buckhead. Good production quality. 4–8 person format. High communication activity — reveals group dynamics fast.',
    effort: 'medium', distance: 'ITP', timeOfDay: 'evening', bestDays: 'any',
    duration: '1hr', groupSize: 'group',
    free: false, cost: '$28–35/person', membershipIncluded: false, membershipVenue: null,
    ticketsRequired: true, papaFriendly: false, rubyFriendly: false,
    deanScore: 1, parentScore: 4,
    address: '3393 Peachtree Rd NE, Atlanta, GA', lat: 33.8509, lng: -84.3618,
    url: 'https://escapology.com/en/atlanta', notes: 'Book ahead. Pick a 60-min room for first-timers. Intermediate difficulty recommended.'
  }
];
